<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateRegionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('regions', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('region');
            $table->string('city');
            $table->timestamps();
        });

        DB::table('regions')->insert([
            ['region'=>'Kampala Region', 'city'=>'Bugolobi'],
            ['region'=>'Kampala Region', 'city'=>'Bukasa'],
            ['region'=>'Kampala Region', 'city'=>'Bukesa'],
            ['region'=>'Kampala Region', 'city'=>'Bukoto'],
            ['region'=>'Kampala Region', 'city'=>'Bulenga'],
            ['region'=>'Kampala Region', 'city'=>'Bunga'],
            ['region'=>'Kampala Region', 'city'=>'Busega'],
            ['region'=>'Kampala Region', 'city'=>'Butabika'],
            ['region'=>'Kampala Region', 'city'=>'Buwate'],
            ['region'=>'Kampala Region', 'city'=>'Buziga'],
            ['region'=>'Kampala Region', 'city'=>'Bwaise'],
            ['region'=>'Kampala Region', 'city'=>'Bweyogerere'],
            ['region'=>'Kampala Region', 'city'=>'Central Business District'],
            ['region'=>'Kampala Region', 'city'=>'Downtown Kampala'],
            ['region'=>'Kampala Region', 'city'=>'Ggaba'],
            ['region'=>'Kampala Region', 'city'=>'Kabalagala'],
            ['region'=>'Kampala Region', 'city'=>'Kabojja'],
            ['region'=>'Kampala Region', 'city'=>'Kabowa'],
            ['region'=>'Kampala Region', 'city'=>'Kabuusu'],
            ['region'=>'Kampala Region', 'city'=>'Kagoma'],
            ['region'=>'Kampala Region', 'city'=>'Kalerwe'],
            ['region'=>'Kampala Region', 'city'=>'Kampala Industrial Area'],
            ['region'=>'Kampala Region', 'city'=>'Kamwanyi'],
            ['region'=>'Kampala Region', 'city'=>'Kamwokya'],
            ['region'=>'Kampala Region', 'city'=>'Kansanga'],
            ['region'=>'Kampala Region', 'city'=>'Kanyanya'],
            ['region'=>'Kampala Region', 'city'=>'Kasubi'],
            ['region'=>'Kampala Region', 'city'=>'Katwe'],
            ['region'=>'Kampala Region', 'city'=>'Kawaala'],
            ['region'=>'Kampala Region', 'city'=>'Kawempe'],
            ['region'=>'Kampala Region', 'city'=>'Kazo'],
            ['region'=>'Kampala Region', 'city'=>'Kibiri'],
            ['region'=>'Kampala Region', 'city'=>'Kibu'],
            ['region'=>'Kampala Region', 'city'=>'Kibuye'],
            ['region'=>'Kampala Region', 'city'=>'Kigowa'],
            ['region'=>'Kampala Region', 'city'=>'Kikaya'],
            ['region'=>'Kampala Region', 'city'=>'Kikoni'],
            ['region'=>'Kampala Region', 'city'=>'Kinawataka'],
            ['region'=>'Kampala Region', 'city'=>'Kira'],
            ['region'=>'Kampala Region', 'city'=>'Kireka'],
            ['region'=>'Kampala Region', 'city'=>'Kirinya'],
            ['region'=>'Kampala Region', 'city'=>'Kirombe'],
            ['region'=>'Kampala Region', 'city'=>'Kisaasi'],
            ['region'=>'Kampala Region', 'city'=>'Kisenyi'],
            ['region'=>'Kampala Region', 'city'=>'Kisugu'],
            ['region'=>'Kampala Region', 'city'=>'Kiswa'],
            ['region'=>'Kampala Region', 'city'=>'Kitala'],
            ['region'=>'Kampala Region', 'city'=>'Kitante'],
            ['region'=>'Kampala Region', 'city'=>'Kitebi'],
            ['region'=>'Kampala Region', 'city'=>'Kitintale'],
            ['region'=>'Kampala Region', 'city'=>'Kiwatule'],
            ['region'=>'Kampala Region', 'city'=>'Kololo'],
            ['region'=>'Kampala Region', 'city'=>'Komamboga'],
            ['region'=>'Kampala Region', 'city'=>'Kulambiro'],
            ['region'=>'Kampala Region', 'city'=>'Kyaliwajjala'],
            ['region'=>'Kampala Region', 'city'=>'Kyambogo'],
            ['region'=>'Kampala Region', 'city'=>'Kyanja'],
            ['region'=>'Kampala Region', 'city'=>'Kyebando'],
            ['region'=>'Kampala Region', 'city'=>'Kyengera'],
            ['region'=>'Kampala Region', 'city'=>'Lubowa'],
            ['region'=>'Kampala Region', 'city'=>'Lubya'],
            ['region'=>'Kampala Region', 'city'=>'Lugala'],
            ['region'=>'Kampala Region', 'city'=>'Lugoba'],
            ['region'=>'Kampala Region', 'city'=>'Lugogo'],
            ['region'=>'Kampala Region', 'city'=>'Lungujja'],
            ['region'=>'Kampala Region', 'city'=>'Lusaze'],
            ['region'=>'Kampala Region', 'city'=>'Luwafu'],
            ['region'=>'Kampala Region', 'city'=>'Luzira'],
            ['region'=>'Kampala Region', 'city'=>'Lweza'],
            ['region'=>'Kampala Region', 'city'=>'Maganjo'],
            ['region'=>'Kampala Region', 'city'=>'Makerere'],
            ['region'=>'Kampala Region', 'city'=>'Makindye'],
            ['region'=>'Kampala Region', 'city'=>'Masanafu'],
            ['region'=>'Kampala Region', 'city'=>'Mawanga'],
            ['region'=>'Kampala Region', 'city'=>'Mbalwa'],
            ['region'=>'Kampala Region', 'city'=>'Mbuya'],
            ['region'=>'Kampala Region', 'city'=>'Mengo'],
            ['region'=>'Kampala Region', 'city'=>'Mpanga'],
            ['region'=>'Kampala Region', 'city'=>'Mpererwe'],
            ['region'=>'Kampala Region', 'city'=>'Mulago'],
            ['region'=>'Kampala Region', 'city'=>'Munyonyo'],
            ['region'=>'Kampala Region', 'city'=>'Mutundwev'],
            ['region'=>'Kampala Region', 'city'=>'Mutungo'],
            ['region'=>'Kampala Region', 'city'=>'Muyenga'],
            ['region'=>'Kampala Region', 'city'=>'Naalaya'],
            ['region'=>'Kampala Region', 'city'=>'Nabisunsa'],
            ['region'=>'Kampala Region', 'city'=>'Naguru'],
            ['region'=>'Kampala Region', 'city'=>'Najjanankumbi'],
            ['region'=>'Kampala Region', 'city'=>'Najjera'],
            ['region'=>'Kampala Region', 'city'=>'Nakasero'],
            ['region'=>'Kampala Region', 'city'=>'Nakawa'],
            ['region'=>'Kampala Region', 'city'=>'Nakivubo'],
            ['region'=>'Kampala Region', 'city'=>'Nalukolongo'],
            ['region'=>'Kampala Region', 'city'=>'Namasuba'],
            ['region'=>'Kampala Region', 'city'=>'Namirembe'],
            ['region'=>'Kampala Region', 'city'=>'Namugongo'],
            ['region'=>'Kampala Region', 'city'=>'Namungona'],
            ['region'=>'Kampala Region', 'city'=>'Namuwongo'],
            ['region'=>'Kampala Region', 'city'=>'Nankulabye'],
            ['region'=>'Kampala Region', 'city'=>'Nansana'],
            ['region'=>'Kampala Region', 'city'=>'Natete'],
            ['region'=>'Kampala Region', 'city'=>'Ndeba'],
            ['region'=>'Kampala Region', 'city'=>'Nsambya'],
            ['region'=>'Kampala Region', 'city'=>'Ntinda'],
            ['region'=>'Kampala Region', 'city'=>'Nyanama'],
            ['region'=>'Kampala Region', 'city'=>'Old Kampala'],
            ['region'=>'Kampala Region', 'city'=>'Rubaga'],
            ['region'=>'Kampala Region', 'city'=>'Salaama'],
            ['region'=>'Kampala Region', 'city'=>'Seguku'],
            ['region'=>'Kampala Region', 'city'=>'Sonde'],
            ['region'=>'Kampala Region', 'city'=>'Wakaliga'],
            ['region'=>'Kampala Region', 'city'=>'Wandegeya'],
            ['region'=>'Kampala Region', 'city'=>'Wankulukuku'],
            ['region'=>'Kampala Region', 'city'=>'Zana'],
            ['region'=>'Entebbe Area', 'city'=>'Abayita Ababili'],
            ['region'=>'Entebbe Area', 'city'=>'Banga'],
            ['region'=>'Entebbe Area', 'city'=>'Bugonga'],
            ['region'=>'Entebbe Area', 'city'=>'Entebbe Market Area'],
            ['region'=>'Entebbe Area', 'city'=>'Entebbe Town'],
            ['region'=>'Entebbe Area', 'city'=>'Katabi'],
            ['region'=>'Entebbe Area', 'city'=>'Kitoro'],
            ['region'=>'Entebbe Area', 'city'=>'Kitubulu'],
            ['region'=>'Entebbe Area', 'city'=>'Kiwafu'],
            ['region'=>'Entebbe Area', 'city'=>'Lunyo'],
            ['region'=>'Entebbe Area', 'city'=>'Manyago'],
            ['region'=>'Entebbe Area', 'city'=>'Nakiwogo'],
            ['region'=>'Entebbe Area', 'city'=>'Nkumba'],
            ['region'=>'Entebbe Area', 'city'=>'Nsamizi'],
            ['region'=>'Eastern Region', 'city'=>'Amoria'],
            ['region'=>'Eastern Region', 'city'=>'Budaka'],
            ['region'=>'Eastern Region', 'city'=>'Bududa'],
            ['region'=>'Eastern Region', 'city'=>'Bugiri'],
            ['region'=>'Eastern Region', 'city'=>'Bukedea'],
            ['region'=>'Eastern Region', 'city'=>'Bukwa'],
            ['region'=>'Eastern Region', 'city'=>'Bulambuli'],
            ['region'=>'Eastern Region', 'city'=>'Busia'],
            ['region'=>'Eastern Region', 'city'=>'Butaleja'],
            ['region'=>'Eastern Region', 'city'=>'Buyende'],
            ['region'=>'Eastern Region', 'city'=>'Iganga'],
            ['region'=>'Eastern Region', 'city'=>'Jinja'],
            ['region'=>'Eastern Region', 'city'=>'Kaberamaido'],
            ['region'=>'Eastern Region', 'city'=>'Kaliro'],
            ['region'=>'Eastern Region', 'city'=>'Kamuli'],
            ['region'=>'Eastern Region', 'city'=>'Kapchorwa'],
            ['region'=>'Eastern Region', 'city'=>'Katakwi'],
            ['region'=>'Eastern Region', 'city'=>'Kibuku'],
            ['region'=>'Eastern Region', 'city'=>'Kumi'],
            ['region'=>'Eastern Region', 'city'=>'Kween'],
            ['region'=>'Eastern Region', 'city'=>'Luuka'],
            ['region'=>'Eastern Region', 'city'=>'Malaba'],
            ['region'=>'Eastern Region', 'city'=>'Manafwa'],
            ['region'=>'Eastern Region', 'city'=>'Mayuge'],
            ['region'=>'Eastern Region', 'city'=>'Mbale'],
            ['region'=>'Eastern Region', 'city'=>'Namayingo'],
            ['region'=>'Eastern Region', 'city'=>'Namutumba'],
            ['region'=>'Eastern Region', 'city'=>'Ngora'],
            ['region'=>'Eastern Region', 'city'=>'Pallisa'],
            ['region'=>'Eastern Region', 'city'=>'Serere'],
            ['region'=>'Eastern Region', 'city'=>'Sironko'],
            ['region'=>'Eastern Region', 'city'=>'Soroti'],
            ['region'=>'Eastern Region', 'city'=>'Tororo'],
            ['region'=>'Northern Region', 'city'=>'Abim'],
            ['region'=>'Northern Region', 'city'=>'Adjumani'],
            ['region'=>'Northern Region', 'city'=>'Agago'],
            ['region'=>'Northern Region', 'city'=>'Alebtong'],
            ['region'=>'Northern Region', 'city'=>'Amolatar'],
            ['region'=>'Northern Region', 'city'=>'Amudat'],
            ['region'=>'Northern Region', 'city'=>'Amuru'],
            ['region'=>'Northern Region', 'city'=>'Apak'],
            ['region'=>'Northern Region', 'city'=>'Arua'],
            ['region'=>'Northern Region', 'city'=>'Dokolo'],
            ['region'=>'Northern Region', 'city'=>'Gulu'],
            ['region'=>'Northern Region', 'city'=>'Kaabong'],
            ['region'=>'Northern Region', 'city'=>'Kitgum'],
            ['region'=>'Northern Region', 'city'=>'Koboko'],
            ['region'=>'Northern Region', 'city'=>'Kole'],
            ['region'=>'Northern Region', 'city'=>'Kotido'],
            ['region'=>'Northern Region', 'city'=>'Lamwo'],
            ['region'=>'Northern Region', 'city'=>'Lira'],
            ['region'=>'Northern Region', 'city'=>'Maracha'],
            ['region'=>'Northern Region', 'city'=>'Moroto'],
            ['region'=>'Northern Region', 'city'=>'Moyo'],
            ['region'=>'Northern Region', 'city'=>'Nakapiripirit'],
            ['region'=>'Northern Region', 'city'=>'Napak'],
            ['region'=>'Northern Region', 'city'=>'Nebbi'],
            ['region'=>'Northern Region', 'city'=>'Mwoya'],
            ['region'=>'Northern Region', 'city'=>'Otuke'],
            ['region'=>'Northern Region', 'city'=>'Oyam'],
            ['region'=>'Northern Region', 'city'=>'Packwach'],
            ['region'=>'Northern Region', 'city'=>'Padar'],
            ['region'=>'Northern Region', 'city'=>'Yumbe'],
            ['region'=>'Northern Region', 'city'=>'Zombo'],
            ['region'=>'Rest of Central Region', 'city'=>'Akright City'],
            ['region'=>'Rest of Central Region', 'city'=>'Buikwa'],
            ['region'=>'Rest of Central Region', 'city'=>'Bukomansimbi'],
            ['region'=>'Rest of Central Region', 'city'=>'Butambala'],
            ['region'=>'Rest of Central Region', 'city'=>'Buvuma'],
            ['region'=>'Rest of Central Region', 'city'=>'Gayaza'],
            ['region'=>'Rest of Central Region', 'city'=>'Gomba'],
            ['region'=>'Rest of Central Region', 'city'=>'Kajjansi'],
            ['region'=>'Rest of Central Region', 'city'=>'Kakiri'],
            ['region'=>'Rest of Central Region', 'city'=>'Kalangala'],
            ['region'=>'Rest of Central Region', 'city'=>'Kalungu'],
            ['region'=>'Rest of Central Region', 'city'=>'Kasangati'],
            ['region'=>'Rest of Central Region', 'city'=>'Kayunga'],
            ['region'=>'Rest of Central Region', 'city'=>'Kiboga'],
            ['region'=>'Rest of Central Region', 'city'=>'Kikajjo'],
            ['region'=>'Rest of Central Region', 'city'=>'Kisubi'],
            ['region'=>'Rest of Central Region', 'city'=>'Kitende'],
            ['region'=>'Rest of Central Region', 'city'=>'Kyankwanzi'],
            ['region'=>'Rest of Central Region', 'city'=>'Kyotera'],
            ['region'=>'Rest of Central Region', 'city'=>'Lugazi'],
            ['region'=>'Rest of Central Region', 'city'=>'Luwero'],
            ['region'=>'Rest of Central Region', 'city'=>'Lwengo'],
            ['region'=>'Rest of Central Region', 'city'=>'Lyantonde'],
            ['region'=>'Rest of Central Region', 'city'=>'Masaka'],
            ['region'=>'Rest of Central Region', 'city'=>'Matugga'],
            ['region'=>'Rest of Central Region', 'city'=>'Mityana'],
            ['region'=>'Rest of Central Region', 'city'=>'Mpigi'],
            ['region'=>'Rest of Central Region', 'city'=>'Mubende'],
            ['region'=>'Rest of Central Region', 'city'=>'Mukono'],
            ['region'=>'Rest of Central Region', 'city'=>'Nakaseke'],
            ['region'=>'Rest of Central Region', 'city'=>'Nakasongola'],
            ['region'=>'Rest of Central Region', 'city'=>'Namulanda'],
            ['region'=>'Rest of Central Region', 'city'=>'Nsangi'],
            ['region'=>'Rest of Central Region', 'city'=>'Nsansa'],
            ['region'=>'Rest of Central Region', 'city'=>'Rakai'],
            ['region'=>'Rest of Central Region', 'city'=>'Seeta'],
            ['region'=>'Rest of Central Region', 'city'=>'Sembabule'],
            ['region'=>'Rest of Central Region', 'city'=>'Wakiso'],
            ['region'=>'Rest of Central Region', 'city'=>'Wampewo'],
            ['region'=>'Western Region', 'city'=>'Buhweju'],
            ['region'=>'Western Region', 'city'=>'Buliisa'],
            ['region'=>'Western Region', 'city'=>'Bundibujo'],
            ['region'=>'Western Region', 'city'=>'Bushenyi'],
            ['region'=>'Western Region', 'city'=>'Hoima'],
            ['region'=>'Western Region', 'city'=>'Ibanda'],
            ['region'=>'Western Region', 'city'=>'Isingiro'],
            ['region'=>'Western Region', 'city'=>'Kabale'],
            ['region'=>'Western Region', 'city'=>'Kabarole'],
            ['region'=>'Western Region', 'city'=>'Kamwenge'],
            ['region'=>'Western Region', 'city'=>'Kanungu'],
            ['region'=>'Western Region', 'city'=>'Kasese'],
            ['region'=>'Western Region', 'city'=>'Kibaale'],
            ['region'=>'Western Region', 'city'=>'Kiruhura'],
            ['region'=>'Western Region', 'city'=>'Kiryandongo'],
            ['region'=>'Western Region', 'city'=>'Kisoro'],
            ['region'=>'Western Region', 'city'=>'Kyegegwa'],
            ['region'=>'Western Region', 'city'=>'Kyenjojo'],
            ['region'=>'Western Region', 'city'=>'Masindi'],
            ['region'=>'Western Region', 'city'=>'Mbarara'],
            ['region'=>'Western Region', 'city'=>'Mitooma'],
            ['region'=>'Western Region', 'city'=>'Ntoroko'],
            ['region'=>'Western Region', 'city'=>'Ntungamo'],
            ['region'=>'Western Region', 'city'=>'Ruburizi'],
            ['region'=>'Western Region', 'city'=>'Rukungiri'],
            ['region'=>'Western Region', 'city'=>'Sheema']
            ]);
            

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('regions');
    }
}
