<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateRegionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('regions', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('region', 50);
            $table->string('town', 50);
            $table->timestamps();
        });

        DB::table('regions')->insert([
            ['region'=>'Kampala Region', 'town'=>'Bugolobi'],
            ['region'=>'Kampala Region', 'town'=>'Bukasa'],
            ['region'=>'Kampala Region', 'town'=>'Bukesa'],
            ['region'=>'Kampala Region', 'town'=>'Bukoto'],
            ['region'=>'Kampala Region', 'town'=>'Bulenga'],
            ['region'=>'Kampala Region', 'town'=>'Bunga'],
            ['region'=>'Kampala Region', 'town'=>'Busega'],
            ['region'=>'Kampala Region', 'town'=>'Butabika'],
            ['region'=>'Kampala Region', 'town'=>'Buwate'],
            ['region'=>'Kampala Region', 'town'=>'Buziga'],
            ['region'=>'Kampala Region', 'town'=>'Bwaise'],
            ['region'=>'Kampala Region', 'town'=>'Bweyogerere'],
            ['region'=>'Kampala Region', 'town'=>'Central Business District'],
            ['region'=>'Kampala Region', 'town'=>'Downtown Kampala'],
            ['region'=>'Kampala Region', 'town'=>'Ggaba'],
            ['region'=>'Kampala Region', 'town'=>'Kabalagala'],
            ['region'=>'Kampala Region', 'town'=>'Kabojja'],
            ['region'=>'Kampala Region', 'town'=>'Kabowa'],
            ['region'=>'Kampala Region', 'town'=>'Kabuusu'],
            ['region'=>'Kampala Region', 'town'=>'Kagoma'],
            ['region'=>'Kampala Region', 'town'=>'Kalerwe'],
            ['region'=>'Kampala Region', 'town'=>'Kampala Industrial Area'],
            ['region'=>'Kampala Region', 'town'=>'Kamwanyi'],
            ['region'=>'Kampala Region', 'town'=>'Kamwokya'],
            ['region'=>'Kampala Region', 'town'=>'Kansanga'],
            ['region'=>'Kampala Region', 'town'=>'Kanyanya'],
            ['region'=>'Kampala Region', 'town'=>'Kasubi'],
            ['region'=>'Kampala Region', 'town'=>'Katwe'],
            ['region'=>'Kampala Region', 'town'=>'Kawaala'],
            ['region'=>'Kampala Region', 'town'=>'Kawempe'],
            ['region'=>'Kampala Region', 'town'=>'Kazo'],
            ['region'=>'Kampala Region', 'town'=>'Kibiri'],
            ['region'=>'Kampala Region', 'town'=>'Kibu'],
            ['region'=>'Kampala Region', 'town'=>'Kibuye'],
            ['region'=>'Kampala Region', 'town'=>'Kigowa'],
            ['region'=>'Kampala Region', 'town'=>'Kikaya'],
            ['region'=>'Kampala Region', 'town'=>'Kikoni'],
            ['region'=>'Kampala Region', 'town'=>'Kinawataka'],
            ['region'=>'Kampala Region', 'town'=>'Kira'],
            ['region'=>'Kampala Region', 'town'=>'Kireka'],
            ['region'=>'Kampala Region', 'town'=>'Kirinya'],
            ['region'=>'Kampala Region', 'town'=>'Kirombe'],
            ['region'=>'Kampala Region', 'town'=>'Kisaasi'],
            ['region'=>'Kampala Region', 'town'=>'Kisenyi'],
            ['region'=>'Kampala Region', 'town'=>'Kisugu'],
            ['region'=>'Kampala Region', 'town'=>'Kiswa'],
            ['region'=>'Kampala Region', 'town'=>'Kitala'],
            ['region'=>'Kampala Region', 'town'=>'Kitante'],
            ['region'=>'Kampala Region', 'town'=>'Kitebi'],
            ['region'=>'Kampala Region', 'town'=>'Kitintale'],
            ['region'=>'Kampala Region', 'town'=>'Kiwatule'],
            ['region'=>'Kampala Region', 'town'=>'Kololo'],
            ['region'=>'Kampala Region', 'town'=>'Komamboga'],
            ['region'=>'Kampala Region', 'town'=>'Kulambiro'],
            ['region'=>'Kampala Region', 'town'=>'Kyaliwajjala'],
            ['region'=>'Kampala Region', 'town'=>'Kyambogo'],
            ['region'=>'Kampala Region', 'town'=>'Kyanja'],
            ['region'=>'Kampala Region', 'town'=>'Kyebando'],
            ['region'=>'Kampala Region', 'town'=>'Kyengera'],
            ['region'=>'Kampala Region', 'town'=>'Lubowa'],
            ['region'=>'Kampala Region', 'town'=>'Lubya'],
            ['region'=>'Kampala Region', 'town'=>'Lugala'],
            ['region'=>'Kampala Region', 'town'=>'Lugoba'],
            ['region'=>'Kampala Region', 'town'=>'Lugogo'],
            ['region'=>'Kampala Region', 'town'=>'Lungujja'],
            ['region'=>'Kampala Region', 'town'=>'Lusaze'],
            ['region'=>'Kampala Region', 'town'=>'Luwafu'],
            ['region'=>'Kampala Region', 'town'=>'Luzira'],
            ['region'=>'Kampala Region', 'town'=>'Lweza'],
            ['region'=>'Kampala Region', 'town'=>'Maganjo'],
            ['region'=>'Kampala Region', 'town'=>'Makerere'],
            ['region'=>'Kampala Region', 'town'=>'Makindye'],
            ['region'=>'Kampala Region', 'town'=>'Masanafu'],
            ['region'=>'Kampala Region', 'town'=>'Mawanga'],
            ['region'=>'Kampala Region', 'town'=>'Mbalwa'],
            ['region'=>'Kampala Region', 'town'=>'Mbuya'],
            ['region'=>'Kampala Region', 'town'=>'Mengo'],
            ['region'=>'Kampala Region', 'town'=>'Mpanga'],
            ['region'=>'Kampala Region', 'town'=>'Mpererwe'],
            ['region'=>'Kampala Region', 'town'=>'Mulago'],
            ['region'=>'Kampala Region', 'town'=>'Munyonyo'],
            ['region'=>'Kampala Region', 'town'=>'Mutundwev'],
            ['region'=>'Kampala Region', 'town'=>'Mutungo'],
            ['region'=>'Kampala Region', 'town'=>'Muyenga'],
            ['region'=>'Kampala Region', 'town'=>'Naalaya'],
            ['region'=>'Kampala Region', 'town'=>'Nabisunsa'],
            ['region'=>'Kampala Region', 'town'=>'Naguru'],
            ['region'=>'Kampala Region', 'town'=>'Najjanankumbi'],
            ['region'=>'Kampala Region', 'town'=>'Najjera'],
            ['region'=>'Kampala Region', 'town'=>'Nakasero'],
            ['region'=>'Kampala Region', 'town'=>'Nakawa'],
            ['region'=>'Kampala Region', 'town'=>'Nakivubo'],
            ['region'=>'Kampala Region', 'town'=>'Nalukolongo'],
            ['region'=>'Kampala Region', 'town'=>'Namasuba'],
            ['region'=>'Kampala Region', 'town'=>'Namirembe'],
            ['region'=>'Kampala Region', 'town'=>'Namugongo'],
            ['region'=>'Kampala Region', 'town'=>'Namungona'],
            ['region'=>'Kampala Region', 'town'=>'Namuwongo'],
            ['region'=>'Kampala Region', 'town'=>'Nankulabye'],
            ['region'=>'Kampala Region', 'town'=>'Nansana'],
            ['region'=>'Kampala Region', 'town'=>'Natete'],
            ['region'=>'Kampala Region', 'town'=>'Ndeba'],
            ['region'=>'Kampala Region', 'town'=>'Nsambya'],
            ['region'=>'Kampala Region', 'town'=>'Ntinda'],
            ['region'=>'Kampala Region', 'town'=>'Nyanama'],
            ['region'=>'Kampala Region', 'town'=>'Old Kampala'],
            ['region'=>'Kampala Region', 'town'=>'Rubaga'],
            ['region'=>'Kampala Region', 'town'=>'Salaama'],
            ['region'=>'Kampala Region', 'town'=>'Seguku'],
            ['region'=>'Kampala Region', 'town'=>'Sonde'],
            ['region'=>'Kampala Region', 'town'=>'Wakaliga'],
            ['region'=>'Kampala Region', 'town'=>'Wandegeya'],
            ['region'=>'Kampala Region', 'town'=>'Wankulukuku'],
            ['region'=>'Kampala Region', 'town'=>'Zana'],
            ['region'=>'Entebbe Area', 'town'=>'Abayita Ababili'],
            ['region'=>'Entebbe Area', 'town'=>'Banga'],
            ['region'=>'Entebbe Area', 'town'=>'Bugonga'],
            ['region'=>'Entebbe Area', 'town'=>'Entebbe Market Area'],
            ['region'=>'Entebbe Area', 'town'=>'Entebbe Town'],
            ['region'=>'Entebbe Area', 'town'=>'Katabi'],
            ['region'=>'Entebbe Area', 'town'=>'Kitoro'],
            ['region'=>'Entebbe Area', 'town'=>'Kitubulu'],
            ['region'=>'Entebbe Area', 'town'=>'Kiwafu'],
            ['region'=>'Entebbe Area', 'town'=>'Lunyo'],
            ['region'=>'Entebbe Area', 'town'=>'Manyago'],
            ['region'=>'Entebbe Area', 'town'=>'Nakiwogo'],
            ['region'=>'Entebbe Area', 'town'=>'Nkumba'],
            ['region'=>'Entebbe Area', 'town'=>'Nsamizi'],
            ['region'=>'Eastern Region', 'town'=>'Amoria'],
            ['region'=>'Eastern Region', 'town'=>'Budaka'],
            ['region'=>'Eastern Region', 'town'=>'Bududa'],
            ['region'=>'Eastern Region', 'town'=>'Bugiri'],
            ['region'=>'Eastern Region', 'town'=>'Bukedea'],
            ['region'=>'Eastern Region', 'town'=>'Bukwa'],
            ['region'=>'Eastern Region', 'town'=>'Bulambuli'],
            ['region'=>'Eastern Region', 'town'=>'Busia'],
            ['region'=>'Eastern Region', 'town'=>'Butaleja'],
            ['region'=>'Eastern Region', 'town'=>'Buyende'],
            ['region'=>'Eastern Region', 'town'=>'Iganga'],
            ['region'=>'Eastern Region', 'town'=>'Jinja'],
            ['region'=>'Eastern Region', 'town'=>'Kaberamaido'],
            ['region'=>'Eastern Region', 'town'=>'Kaliro'],
            ['region'=>'Eastern Region', 'town'=>'Kamuli'],
            ['region'=>'Eastern Region', 'town'=>'Kapchorwa'],
            ['region'=>'Eastern Region', 'town'=>'Katakwi'],
            ['region'=>'Eastern Region', 'town'=>'Kibuku'],
            ['region'=>'Eastern Region', 'town'=>'Kumi'],
            ['region'=>'Eastern Region', 'town'=>'Kween'],
            ['region'=>'Eastern Region', 'town'=>'Luuka'],
            ['region'=>'Eastern Region', 'town'=>'Malaba'],
            ['region'=>'Eastern Region', 'town'=>'Manafwa'],
            ['region'=>'Eastern Region', 'town'=>'Mayuge'],
            ['region'=>'Eastern Region', 'town'=>'Mbale'],
            ['region'=>'Eastern Region', 'town'=>'Namayingo'],
            ['region'=>'Eastern Region', 'town'=>'Namutumba'],
            ['region'=>'Eastern Region', 'town'=>'Ngora'],
            ['region'=>'Eastern Region', 'town'=>'Pallisa'],
            ['region'=>'Eastern Region', 'town'=>'Serere'],
            ['region'=>'Eastern Region', 'town'=>'Sironko'],
            ['region'=>'Eastern Region', 'town'=>'Soroti'],
            ['region'=>'Eastern Region', 'town'=>'Tororo'],
            ['region'=>'Northern Region', 'town'=>'Abim'],
            ['region'=>'Northern Region', 'town'=>'Adjumani'],
            ['region'=>'Northern Region', 'town'=>'Agago'],
            ['region'=>'Northern Region', 'town'=>'Alebtong'],
            ['region'=>'Northern Region', 'town'=>'Amolatar'],
            ['region'=>'Northern Region', 'town'=>'Amudat'],
            ['region'=>'Northern Region', 'town'=>'Amuru'],
            ['region'=>'Northern Region', 'town'=>'Apak'],
            ['region'=>'Northern Region', 'town'=>'Arua'],
            ['region'=>'Northern Region', 'town'=>'Dokolo'],
            ['region'=>'Northern Region', 'town'=>'Gulu'],
            ['region'=>'Northern Region', 'town'=>'Kaabong'],
            ['region'=>'Northern Region', 'town'=>'Kitgum'],
            ['region'=>'Northern Region', 'town'=>'Koboko'],
            ['region'=>'Northern Region', 'town'=>'Kole'],
            ['region'=>'Northern Region', 'town'=>'Kotido'],
            ['region'=>'Northern Region', 'town'=>'Lamwo'],
            ['region'=>'Northern Region', 'town'=>'Lira'],
            ['region'=>'Northern Region', 'town'=>'Maracha'],
            ['region'=>'Northern Region', 'town'=>'Moroto'],
            ['region'=>'Northern Region', 'town'=>'Moyo'],
            ['region'=>'Northern Region', 'town'=>'Nakapiripirit'],
            ['region'=>'Northern Region', 'town'=>'Napak'],
            ['region'=>'Northern Region', 'town'=>'Nebbi'],
            ['region'=>'Northern Region', 'town'=>'Mwoya'],
            ['region'=>'Northern Region', 'town'=>'Otuke'],
            ['region'=>'Northern Region', 'town'=>'Oyam'],
            ['region'=>'Northern Region', 'town'=>'Packwach'],
            ['region'=>'Northern Region', 'town'=>'Padar'],
            ['region'=>'Northern Region', 'town'=>'Yumbe'],
            ['region'=>'Northern Region', 'town'=>'Zombo'],
            ['region'=>'Rest of Central Region', 'town'=>'Akright town'],
            ['region'=>'Rest of Central Region', 'town'=>'Buikwa'],
            ['region'=>'Rest of Central Region', 'town'=>'Bukomansimbi'],
            ['region'=>'Rest of Central Region', 'town'=>'Butambala'],
            ['region'=>'Rest of Central Region', 'town'=>'Buvuma'],
            ['region'=>'Rest of Central Region', 'town'=>'Gayaza'],
            ['region'=>'Rest of Central Region', 'town'=>'Gomba'],
            ['region'=>'Rest of Central Region', 'town'=>'Kajjansi'],
            ['region'=>'Rest of Central Region', 'town'=>'Kakiri'],
            ['region'=>'Rest of Central Region', 'town'=>'Kalangala'],
            ['region'=>'Rest of Central Region', 'town'=>'Kalungu'],
            ['region'=>'Rest of Central Region', 'town'=>'Kasangati'],
            ['region'=>'Rest of Central Region', 'town'=>'Kayunga'],
            ['region'=>'Rest of Central Region', 'town'=>'Kiboga'],
            ['region'=>'Rest of Central Region', 'town'=>'Kikajjo'],
            ['region'=>'Rest of Central Region', 'town'=>'Kisubi'],
            ['region'=>'Rest of Central Region', 'town'=>'Kitende'],
            ['region'=>'Rest of Central Region', 'town'=>'Kyankwanzi'],
            ['region'=>'Rest of Central Region', 'town'=>'Kyotera'],
            ['region'=>'Rest of Central Region', 'town'=>'Lugazi'],
            ['region'=>'Rest of Central Region', 'town'=>'Luwero'],
            ['region'=>'Rest of Central Region', 'town'=>'Lwengo'],
            ['region'=>'Rest of Central Region', 'town'=>'Lyantonde'],
            ['region'=>'Rest of Central Region', 'town'=>'Masaka'],
            ['region'=>'Rest of Central Region', 'town'=>'Matugga'],
            ['region'=>'Rest of Central Region', 'town'=>'Mityana'],
            ['region'=>'Rest of Central Region', 'town'=>'Mpigi'],
            ['region'=>'Rest of Central Region', 'town'=>'Mubende'],
            ['region'=>'Rest of Central Region', 'town'=>'Mukono'],
            ['region'=>'Rest of Central Region', 'town'=>'Nakaseke'],
            ['region'=>'Rest of Central Region', 'town'=>'Nakasongola'],
            ['region'=>'Rest of Central Region', 'town'=>'Namulanda'],
            ['region'=>'Rest of Central Region', 'town'=>'Nsangi'],
            ['region'=>'Rest of Central Region', 'town'=>'Nsansa'],
            ['region'=>'Rest of Central Region', 'town'=>'Rakai'],
            ['region'=>'Rest of Central Region', 'town'=>'Seeta'],
            ['region'=>'Rest of Central Region', 'town'=>'Sembabule'],
            ['region'=>'Rest of Central Region', 'town'=>'Wakiso'],
            ['region'=>'Rest of Central Region', 'town'=>'Wampewo'],
            ['region'=>'Western Region', 'town'=>'Buhweju'],
            ['region'=>'Western Region', 'town'=>'Buliisa'],
            ['region'=>'Western Region', 'town'=>'Bundibujo'],
            ['region'=>'Western Region', 'town'=>'Bushenyi'],
            ['region'=>'Western Region', 'town'=>'Hoima'],
            ['region'=>'Western Region', 'town'=>'Ibanda'],
            ['region'=>'Western Region', 'town'=>'Isingiro'],
            ['region'=>'Western Region', 'town'=>'Kabale'],
            ['region'=>'Western Region', 'town'=>'Kabarole'],
            ['region'=>'Western Region', 'town'=>'Kamwenge'],
            ['region'=>'Western Region', 'town'=>'Kanungu'],
            ['region'=>'Western Region', 'town'=>'Kasese'],
            ['region'=>'Western Region', 'town'=>'Kibaale'],
            ['region'=>'Western Region', 'town'=>'Kiruhura'],
            ['region'=>'Western Region', 'town'=>'Kiryandongo'],
            ['region'=>'Western Region', 'town'=>'Kisoro'],
            ['region'=>'Western Region', 'town'=>'Kyegegwa'],
            ['region'=>'Western Region', 'town'=>'Kyenjojo'],
            ['region'=>'Western Region', 'town'=>'Masindi'],
            ['region'=>'Western Region', 'town'=>'Mbarara'],
            ['region'=>'Western Region', 'town'=>'Mitooma'],
            ['region'=>'Western Region', 'town'=>'Ntoroko'],
            ['region'=>'Western Region', 'town'=>'Ntungamo'],
            ['region'=>'Western Region', 'town'=>'Ruburizi'],
            ['region'=>'Western Region', 'town'=>'Rukungiri'],
            ['region'=>'Western Region', 'town'=>'Sheema']
            ]);
            

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('regions');
    }
}
